<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="unittest_tests.SimpleTest-20211219173501" tests="3" file="unittest_tests.py" time="2.218" timestamp="2021-12-19T17:35:08" failures="3" errors="0" skipped="0">
	<testcase classname="unittest_tests.SimpleTest" name="testcase1" time="2.177" timestamp="2021-12-19T17:35:08">
		<failure type="AssertionError" message="'Please consult a doctor. Based on your inputs you are likely to get stroke.' != 'Congratulations! Based on your inputs you are not likely to get a stroke.'
- Please consult a doctor. Based on your inputs you are likely to get stroke.
? ^ - ^^^^   ^^^^^^^^^^^^^
+ Congratulations! Based on your inputs you are not likely to get a stroke.
? ^^^^^^^^  ^^   ^                             ++++              ++
"><![CDATA[Traceback (most recent call last):
  File "C:\Users\aksha\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\aksha\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "C:\Users\aksha\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 550, in _callTestMethod
    method()
  File "c:\users\aksha\desktop\stroke-prediction\pybuilder\src\unittest\python\unittest_tests.py", line 21, in testcase1
    self.assertEquals(predict_stroke(case_1), "Congratulations! Based on your inputs you are not likely to get a stroke.")
  File "C:\Users\aksha\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 1327, in deprecated_func
    return original_func(*args, **kwargs)
  File "C:\Users\aksha\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\aksha\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 1209, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\aksha\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 668, in fail
    raise self.failureException(msg)
AssertionError: 'Please consult a doctor. Based on your inputs you are likely to get stroke.' != 'Congratulations! Based on your inputs you are not likely to get a stroke.'
- Please consult a doctor. Based on your inputs you are likely to get stroke.
? ^ - ^^^^   ^^^^^^^^^^^^^
+ Congratulations! Based on your inputs you are not likely to get a stroke.
? ^^^^^^^^  ^^   ^                             ++++              ++

]]></failure>
	</testcase>
	<testcase classname="unittest_tests.SimpleTest" name="testcase2" time="0.022" timestamp="2021-12-19T17:35:08">
		<failure type="AssertionError" message="'Please consult a doctor. Based on your inputs you are likely to get stroke.' != 'Congratulations! Based on your inputs you are not likely to get a stroke.'
- Please consult a doctor. Based on your inputs you are likely to get stroke.
? ^ - ^^^^   ^^^^^^^^^^^^^
+ Congratulations! Based on your inputs you are not likely to get a stroke.
? ^^^^^^^^  ^^   ^                             ++++              ++
"><![CDATA[Traceback (most recent call last):
  File "C:\Users\aksha\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\aksha\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "C:\Users\aksha\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 550, in _callTestMethod
    method()
  File "c:\users\aksha\desktop\stroke-prediction\pybuilder\src\unittest\python\unittest_tests.py", line 37, in testcase2
    self.assertEquals(predict_stroke(case_2), "Congratulations! Based on your inputs you are not likely to get a stroke.")
  File "C:\Users\aksha\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 1327, in deprecated_func
    return original_func(*args, **kwargs)
  File "C:\Users\aksha\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\aksha\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 1209, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\aksha\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 668, in fail
    raise self.failureException(msg)
AssertionError: 'Please consult a doctor. Based on your inputs you are likely to get stroke.' != 'Congratulations! Based on your inputs you are not likely to get a stroke.'
- Please consult a doctor. Based on your inputs you are likely to get stroke.
? ^ - ^^^^   ^^^^^^^^^^^^^
+ Congratulations! Based on your inputs you are not likely to get a stroke.
? ^^^^^^^^  ^^   ^                             ++++              ++

]]></failure>
	</testcase>
	<testcase classname="unittest_tests.SimpleTest" name="testcase3" time="0.019" timestamp="2021-12-19T17:35:08">
		<failure type="AssertionError" message="'Congratulations! Based on your inputs you are not likely to get a stroke.' != 'Please consult a doctor. Based on your inputs you are likely to get stroke.'
- Congratulations! Based on your inputs you are not likely to get a stroke.
+ Please consult a doctor. Based on your inputs you are likely to get stroke.
"><![CDATA[Traceback (most recent call last):
  File "C:\Users\aksha\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\aksha\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "C:\Users\aksha\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 550, in _callTestMethod
    method()
  File "c:\users\aksha\desktop\stroke-prediction\pybuilder\src\unittest\python\unittest_tests.py", line 53, in testcase3
    self.assertEquals(predict_stroke(case_2), "Please consult a doctor. Based on your inputs you are likely to get stroke.")
  File "C:\Users\aksha\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 1327, in deprecated_func
    return original_func(*args, **kwargs)
  File "C:\Users\aksha\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\aksha\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 1209, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\aksha\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 668, in fail
    raise self.failureException(msg)
AssertionError: 'Congratulations! Based on your inputs you are not likely to get a stroke.' != 'Please consult a doctor. Based on your inputs you are likely to get stroke.'
- Congratulations! Based on your inputs you are not likely to get a stroke.
+ Please consult a doctor. Based on your inputs you are likely to get stroke.

]]></failure>
	</testcase>
</testsuite>
